#!/usr/bin/env bash

set -euf -o pipefail

function cask() {
  brew cask install $1
}

function formula() {
  brew install $1
}

brew tap homebrew/cask-versions

cask lastpass
cask caffeine
cask jumpcut
cask spectacle
cask google-chrome
cask spotify
cask zoomus
cask iterm2
cask postman
cask docker
cask gpg-suite
